#!/bin/bash

echo -e "Enter your file name : \c"
read file_name

if [ -f $file_name ]
 then
      if [ -w $file_name ]
      then
        echo "enter your text here...press ctrl+d to quit"
        cat >> $file_name #use ">>" to append to file. Note: if you use ">" it will overwrite your file instead of append
      else 
        echo "you do not have write permission to this file"
      fi
else
  echo "file not found"
fi

